##
#Plugin: PlayersOnline
#Author: TAT
#CONFIGURATION
##

##
#Config: ShowInfo
#Doing: Activate to output settings to console
#Example: true = activate // false = deactivate
##
ShowInfo: true

##
#Config: Multiworld
#Doing: Activate support for multiworlds
#Example: true = activate // false = deactivate
##
Multiworld: true

##
#Config: UseOP / UsePermissions
#Doing: Here you can activate OP and/or Permissions
#Example: true = activate // false = deactivate
##
UseOP: true
UsePermissions: true

##
#Config: ShowOnLogin
#Doing: Activate show admins online on login
#Example: true = activate // false = deactivate
##
ShowOnLogin: true

##
#Config: Messages
#Doing: Change the different messages
#       %s is text inserted by plugin
##
Messages:
    Admin: "%s Online Admin"
    Admins: "%s Online Admins"
    NoAdmins: "No admins online"
    Player: "%s Online Player"
    Players: "%s Online Players"
    Online: "%s is online!"
    Offline: "%s isn't online!"
    NotAdmin: "%s isn't an admin!"
    Group: "Group: %s"
    World: "World: %s"

##
#Config: AdminGroups
#Doing: Here you can setup the groups in Permissions that are registered as admins by PlayersOnline
#       Every group is setup like this:
#           Groupname in Permissions: Shown name 
#       Remember comma between groups and write the groups between the { and }.
##
AdminGroups: {
    OwnerGroup: Owners,
    SupAdminGroup: Super-Admins,
    AdminGroup: Admins,
    SupModeratorGroup: Super-Moderators,
    ModeratorGroup: Moderators 
}

##
#Config: GroupColors
#Doing: Here you can setup colors for the groups set in PermissionGroups
#       Every group is setup like this:
#           Groupname in Permissions: Color 
#       Remember comma between groups and write the groups between the { and }.
#Colorcodes:
#       aqua
#       black
#       blue
#       dark_aqua
#       dark_blue
#       dark_gray
#       dark_green
#       dark_purple
#       dark_red
#       gold
#       gray
#       green
#       light_purple
#       red
#       white
#       yellow
##
GroupColors: {
    OwnerGroup: gold,
    SupAdminGroup: dark_red,
    AdminGroup: red,
    SupModeratorGroup: dark_aqua,
    ModeratorGroup: aqua
}