name: PlayersOnline
main: dk.earthgame.TAT.PlayersOnline.PlayersOnline
version: 1.0
commands:
    admins:
        description: Show which admins there are online
        usage: /adminsonline [name]
    players:
        description: Show which players there are online
        usage: /adminsonline [name]
    reloadao:
        description: Reload AdminsOnline properties
        usage: /reloadao