name: AdminsOnline
main: dk.earthgame.TAT.AdminsOnline.AdminsOnline
version: 0.7DEV
commands:
    adminsonline:
        description: Show which admins there are online
        usage: /adminsonline [player]
    reloadao:
        description: Reload AdminsOnline properties
        usage: /reloadao